#!/bin/sh
exec 2>&1

mkdir -p /home/electrumx/leveldb
export DB_DIRECTORY=/home/electrumx/leveldb
chown -R electrumx:electrumx /home/electrumx

exec su electrumx -c 'python3 /electrumx/electrumx_server'
