#!/bin/sh
exec 2>&1

mkdir -p $DB_DIRECTORY

if [ ! -e "${SSL_CERTFILE}" ] || [ ! -e "${SSL_KEYFILE}" ]; then
  openssl req -newkey rsa:2048 -sha256 -nodes -x509 -days 365 -subj "/O=electrumX" -keyout "${SSL_KEYFILE}" -out "${SSL_CERTFILE}"
fi

chown -R $APP_USER:$APP_USER $DATA_DIR

exec su $APP_USER -c 'exec python3 $APP_DIR/electrumx_server >> $DATA_DIR/server.log'
